# Header
menu:
  Home: /
  Archives: /archives
  Projects: /projects
  About: /about

# Read More text
excerpt_link: Read More

# Disqus Comments Shortname
disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Widgets List
widgets:
  about: This blog is under heavy development and is currently being used as a learning tool. Please feel free to contact me with suggested changes at calvin.c.holloway@gmail.com <br>
  tags: true
